### ISSUE TITLE
CI freezing

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/iceshrimp_ynh#10]
### Describe the bug

CI (and by extension normal `install`) is freezing due to `corepack` change that makes interactive user prompt upon installation of `yarn`/`pnpm`.

### Logs

CF https://ci-apps.yunohost.org/ci/job/25364, if you run locally with `--debug` you'll see interactive prompt `corepack will now install xxxxxx`.

Solution as per https://github.com/YunoHost-Apps/glitchsoc_ynh/pull/258

**Comment by oufmilo** [comment]
Solved by #11
