### ISSUE TITLE
Question: How to add custom assets?

### ISSUE THREAD

**Issue by alcapurrias** [YunoHost-Apps/iceshrimp_ynh#8]
I tried to add custom CSS and a custom robots.txt in `./custom/assets/` as required, but `npm run gulp` doesn't work with the error `sh: 1: gulp: not found`. How can I get those files ingested?

If you've not done this before, here is the info from Firefish: https://firefish.dev/firefish/firefish#customize - the only difference is using npm for Iceshrimp

**Comment by oufmilo** [comment]
Hello ! 
Iceshrimp is not using npm but yarn 
Maybe you could try with yarn and give me the results?

**Comment by alcapurrias** [comment]
Sorry for the delay, I just got a chance to go in there. Same error re: gulp

```
yarn run v1.22.19
$ gulp build
/bin/sh: 1: gulp: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by oufmilo** [comment]
> Sorry for the delay, I just got a chance to go in there. Same error re: gulp
> 
> ```
> yarn run v1.22.19
> $ gulp build
> /bin/sh: 1: gulp: not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

please try this command:
`yarn run gulp`

**Comment by alcapurrias** [comment]
That is what I ran

**Comment by oufmilo** [comment]
> That is what I ran

In wich files did you try ? You should try here `/var/www/iceshrimp`

**Comment by alcapurrias** [comment]
That is where I ran it

**Comment by oufmilo** [comment]
Ok can you give me the logs please ?

**Comment by alcapurrias** [comment]
I just tried it again and it didn't generate anything in the logs

**Comment by oufmilo** [comment]
> I just tried it again and it didn't generate anything in the logs

I can't help you if you have anything in logs ..

**Comment by alcapurrias** [comment]
Then maybe the readme should note that using custom assets is broken?

**Comment by oufmilo** [comment]
The command works on my server so I guess it's possible to make it work. I don't get any error messages

**Comment by oufmilo** [comment]
I think it's possible to customizing assets by this way 

https://iceshrimp.dev/iceshrimp/iceshrimp/src/branch/dev/docs/post-install.md

**Comment by alcapurrias** [comment]
The process in that link is what I was already doing. I was able to fix it:

`yarn global add gulp-cli`

`yarn install`

Both in /var/www/iceshrimp as root - not sure why yarn isn't installed when the package is, but that's what the problem is.
